### ISSUE TITLE
typescript-rest has no exported member Preprocessor

### ISSUE THREAD

**Issue by kuldeepkrsharma029** [thiagobustamante/typescript-rest#60]
I've been try to write a custom decorator using typescript-rest **Preprocessor**, which is working as expected if I run it in my local.

Here's my code for custom decorator.
```
import { Preprocessor } from "typescript-rest";
import { ForbiddenError } from "typescript-rest/dist/server-errors";
import { logger } from "../middleware/logger-mw";

const secured = (...args: any[]) =>
    async (req: any) => {
        if (args && args.length > 0) {
            let isPermitted: boolean = false;
            logger.info("Verifying The Roles :: " + JSON.stringify(args));
            for (const incRole of args) {
                for (const authObj of req.headers.currentUser.authorities) {
                    if (incRole === authObj.authority) {
                        isPermitted = true;
                        break;
                    }
                }
                if (isPermitted) {
                    break;
                }
            }
            if (isPermitted) {
                logger.info("Roles Permitted To Aceess API :: " + JSON.stringify(args));
            } else {
                logger.error("Acess Forbiden For Roles :: " + JSON.stringify(args));
                throw new ForbiddenError("Access Forbidden For Roles :: " + JSON.stringify(args));
            }
        }
        return req;
    };

export const Permission = (...args: any[]) => Preprocessor(secured.apply(null, args));
```

But as soon as I try run my node application inside docker it gives me below error.

```
> typescript-rest-boilerplate@0.0.1 start /usr/src/app
> ts-node src/app.ts


/usr/src/app/node_modules/ts-node/src/index.ts:296
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/decorators/Permission.ts (1,10): Module '"/usr/src/app/node_modules/typescript-rest/dist/typescript-rest"' has no exported member 'Preprocessor'. (2305)
    at getOutput (/usr/src/app/node_modules/ts-node/src/index.ts:296:15)
    at /usr/src/app/node_modules/ts-node/src/index.ts:325:16
    at Object.compile (/usr/src/app/node_modules/ts-node/src/index.ts:479:11)
    at Module.m._compile (/usr/src/app/node_modules/ts-node/src/index.ts:379:43)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/src/app/node_modules/ts-node/src/index.ts:382:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/src/controllers/UtilityController.ts:4:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/usr/src/app/node_modules/ts-node/src/index.ts:379:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/src/app/node_modules/ts-node/src/index.ts:382:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/src/controllers/index.ts:4:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-rest-boilerplate@0.0.1 start: `ts-node src/app.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript-rest-boilerplate@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-27T16_39_15_515Z-debug.log
```
Below is my Dockerfile
```
# Taking Ubuntu As A Base OS
FROM ubuntu:16.04

#Creating a working directory
WORKDIR /usr/src/app

# Updating the apt repo
RUN rm -rf /var/lib/apt/lists/*
RUN apt-get update

# Installing curl
RUN apt-get install -y curl

#Installing Libfontconfig
RUN apt-get install -y libfontconfig

# Installing nodejs
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

# Setting environment profile variable
# ENV profile prod

# copying the package.json and pakcage-lock.json
COPY package*.json ./
 
RUN apt-get install -y bzip2

# installing modules and their dependency
RUN npm install

# Bundle app source
COPY . .

EXPOSE 3004

CMD ["npm", "start"]

```
### typescript-rest version in package.json
"typescript-rest": "^1.1.1",

### Local Environment Node Version
v8.10.0

**Comment by thiagobustamante** [comment]
Please, try update to 2.0 version
